name: publish_gui_windows-2019

on:
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  BUILD_TYPE: Release
  BUILD_DIR : build
  VC_VERSION : 16
  COMPILE_VERSION : '"Visual Studio 16 2019"'       # Because cmake -G needs " "
  WX_VERSION : 3.2.2.1
  WX_ROOT : ${{github.workspace}}/wxWidgets-3.2.2.1 # Name of the first folder in wx sources archive
  GLUT_VERSION : 2.8.1-1
  GLUT_ROOT : ${{github.workspace}}/freeglut        # Name of the first folder in freeglut archive
  
jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
   
    # DO NOT Download freeglut 3.0.0 MSVC Package. It is buggy for glutWireCube, glutSolid* !!!
    # Keep freeglut 2.8.1
    - name: Install Freeglut dependency
      run: |
        Invoke-WebRequest https://www.transmissionzero.co.uk/files/software/development/GLUT/older/freeglut-MSVC-${{env.GLUT_VERSION}}.mp.zip -OutFile freeglut.zip
        Expand-Archive freeglut.zip -DestinationPath ${{github.workspace}} # create GLUT_ROOT directory

    # TODO : Add WX_VERSION in the artifact name
    - name: Download last wxWidgets compiled
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: publish_wx_windows-2019.yml
        name: windows-archive-vc${{env.VC_VERSION}}
#        name: windows-2019-${{env.WX_VERSION}}-vc${{env.VC_VERSION}}
      
    - name: Install wxWidgets dependency
      run: |
        Expand-Archive wxWidgets-${{env.WX_VERSION}}_vc${{env.VC_VERSION}}_x64_release.zip -DestinationPath ${{github.workspace}} # create WX_ROOT directory

#    - name: Install wxWidgets dependency
#      run: |
#        $WX_ARCHIVE = wxWidgets-${{env.WX_VERSION}}_vc${{env.VC_VERSION}}_x64_release.zip
#        Invoke-WebRequest https://soft.mines-paristech.fr/wxWidgets/$WX_ARCHIVE -OutFile wx.zip
#        Expand-Archive wx.zip -DestinationPath ${{env.WX_ROOT}} # create wxWdgets directory

    # Sources are here: https://www.wxwidgets.org/downloads/
#    - name: Extract wxWidgets sources
#      run: |
#        set-alias sz "$env:ProgramFiles\7-Zip\7z.exe"
#        Invoke-WebRequest https://github.com/wxWidgets/wxWidgets/releases/download/v${{env.WX_VERSION}}/wxWidgets-${{env.WX_VERSION}}.tar.bz2 -OutFile wx.bz2
#        sz x -y wx.bz2 # Unzip
#        sz x -y wx -o${{github.workspace}} # Untar
#        ls ${{env.WX_ROOT}}

    # Setup Visual Studio command prompt
#    - uses: ilammy/msvc-dev-cmd@v1
#      with:
#        arch: x64

#    - name: Compile wxWidgets sources (x64 Release only)
#      run : |
#        cd ${{env.WX_ROOT}}\build\msw
#        set _CL_=/MT
#        msbuild -m:4 -t:build -p:"Configuration=Release;Platform=x64" wx_vc${{env.VC_VERSION}}.sln
        
    - name : Create GUI sample program
      run : |
        cmake -B${{env.BUILD_DIR}} -DwxWidgets_ROOT=${{env.WX_ROOT}} -DGLUT_ROOT=${{env.GLUT_ROOT}}
        cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}} --target package_gui
        $FILE_PATH = Get-ChildItem -Path "${{env.BUILD_DIR}}/${{env.BUILD_TYPE}}/hello*.zip" -File
        echo "MY_FILE=$FILE_PATH" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

    - uses: actions/upload-artifact@v3
      with:
        name: windows-archive
        path: ${{env.MY_FILE}}

  publish:
    needs: build
    # Only ubuntu can upload via ssh
    runs-on: ubuntu-latest
    
    steps:
    - uses: fabien-ors/files-publish-action@v3
      with:
        host: ${{ secrets.CG_HOST }}
        username: ${{ secrets.CG_USR }}
        password: ${{ secrets.CG_PWD }}
        dest-path: "/var/www/html/wxgl"

