name: publish_gui_windows-2019

on:
  push:
    branches: [ main ]
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  BUILD_TYPE: Release
  BUILD_DIR : build
  COMPILE_VERSION : '"Visual Studio 16 2019"' #Because cmake -G needs " "
  WX_ROOT : ${{github.workspace}}/wx
  GLUT_ROOT : ${{github.workspace}}/freeglut #name of the first folder in freeglut archive
jobs:
  
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    
    # https://gist.github.com/dansmith65/7dd950f183af5f5deaf9650f2ad3226c
    - name: Install 7Zip
      run: |
        $dlurl = 'https://7-zip.org/' + (Invoke-WebRequest -UseBasicParsing -Uri 'https://7-zip.org/' | Select-Object -ExpandProperty Links | Where-Object {($_.outerHTML -match 'Download')-and ($_.href -like "a/*") -and ($_.href -like "*-x64.exe")} | Select-Object -First 1 | Select-Object -ExpandProperty href)
        # modified to work without IE
        # above code from: https://perplexity.nl/windows-powershell/installing-or-updating-7-zip-using-powershell/
        $installerPath = Join-Path $env:TEMP (Split-Path $dlurl -Leaf)
        Invoke-WebRequest $dlurl -OutFile $installerPath
        Start-Process -FilePath $installerPath -Args "/S" -Verb RunAs -Wait
        Remove-Item $installerPath

    - name: Install Freeglut dependency
      run: |
        Invoke-WebRequest https://www.transmissionzero.co.uk/files/software/development/GLUT/older/freeglut-MSVC-2.8.1-1.mp.zip -OutFile freeglut.zip
        Expand-Archive .\freeglut.zip -DestinationPath .
        ls freeglut\include

    - name: Install wxWidgets dependency
      run: |
        set-alias sz "$env:ProgramFiles\7-Zip\7z.exe"
        Invoke-WebRequest https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.2.1/wxWidgets-3.2.2.1-headers.7z -OutFile wxHeaders.7z
        sz x wxHeaders.7z -o${{ env.WX_ROOT }}
        Invoke-WebRequest https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.2.1/wxMSW-3.2.2_vc14x_x64_ReleaseDLL.7z -OutFile wxDLL.7z
        sz x wxDLL.7z -o${{ env.WX_ROOT }}
        ls
        ls wx\include
        ls wx\lib

    - name : Create GUI sample program
      run : |
        cmake -B${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE:STRING=${{env.BUILD_TYPE}} -DwxWidgets_ROOT=${{ env.WX_ROOT }} -DGLUT_ROOT=${{ env.GLUT_ROOT }}
        cmake --build ${{env.BUILD_DIR}} --target all

    - name: Upload program to CG repo
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CG_HOST }}
        username: ${{ secrets.CG_USR }}
        password: ${{ secrets.CG_PWD }}
        source: ${{env.BUILD_DIR}}/${{env.BUILD_TYPE}}/hello
        target: /var/www/html/wxgl/ubuntu/
        strip_components: 2

