name: publish_wx_windows-2019

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  WX_VERSION : 3.2.2.1
  WX_ROOT : ${{github.workspace}}/wxWidgets-3.2.2.1 # Name of the folder in wx sources archive
  
jobs:
  build:
    runs-on: windows-2019
    strategy :
      matrix:
        vc: ["16","17"]

    steps:
    # wxWidgets sources are here: https://www.wxwidgets.org/downloads/
    - name: Extract wxWidgets sources
      run: |
        set-alias sz "$env:ProgramFiles\7-Zip\7z.exe"
        Invoke-WebRequest https://github.com/wxWidgets/wxWidgets/releases/download/v${{env.WX_VERSION}}/wxWidgets-${{env.WX_VERSION}}.tar.bz2 -OutFile wx.bz2
        sz x -y wx.bz2 # Unzip
        sz x -y wx -o${{github.workspace}} # Untar
        ls ${{env.WX_ROOT}}

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Compile wxWidgets sources (using Visual Studio shell)
      run : |
        cd ${{env.WX_ROOT}}\build\msw
        set _CL_=/MT
        msbuild -m:4 -t:build -p:"Configuration=Release;Platform=x64" wx_vc${{matrix.vc}}.sln
        
    - name : Package the wxWidgets libraries
      run : |
        Compress-Archive -Path ${{env.WX_ROOT}} -DestinationPath wxWidgets-${{env.WX_VERSION}}_vc${{matrix.vc}}_x64_release.zip
        echo "MY_FILE=wxWidgets-${{env.WX_VERSION}}_vc${{matrix.vc}}_x64_release.zip" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

    - name: Result message
      run: echo "Built ${{env.MY_FILE}}"

    - uses: actions/upload-artifact@v3
      with:
        name: windows-2019-${{env.WX_VERSION}}-vc${{matrix.vc}}
        path: ${{env.MY_FILE}}

    - uses: fabien-ors/files-publish-action@v1
      with:
        host: ${{ secrets.CG_HOST }}
        username: ${{ secrets.CG_USR }}
        password: ${{ secrets.CG_PWD }}
        dest-path: "/var/www/html/wx"
        pattern: "wxWidgets*"