name: publish_gui_ubuntu-latest

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  BUILD_TYPE: Release
  BUILD_DIR : build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: flumy/ubuntu-16-wx

    steps:
    - uses: actions/checkout@v3
        
    - name : Create GUI sample program
      run : |
        cmake -B${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE:STRING=${{env.BUILD_TYPE}}
        cmake --build ${{env.BUILD_DIR}} --target all
        
    - name: Upload program to CG repo
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CG_HOST }}
        username: ${{ secrets.CG_USR }}
        password: ${{ secrets.CG_PWD }}
        source: ${{env.BUILD_DIR}}/${{env.BUILD_TYPE}}/hello
        target: /var/www/html/wxgl/ubuntu/
        strip_components: 2
