name: publish_gui_ubuntu-16

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  BUILD_TYPE: Release
  BUILD_DIR : build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: flumy/ubuntu-16-wx

    steps:
    - uses: actions/checkout@v3

    - name: Create GUI sample program
      run: |
        cmake -B${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE:STRING=${{env.BUILD_TYPE}}
        cmake --build ${{env.BUILD_DIR}} --target package_gui
        echo "MY_FILE=$(ls ${{env.BUILD_DIR}}/${{env.BUILD_TYPE}}/hello*.tar.gz)" >> "$GITHUB_ENV"

    - name: Result message
      run: echo "Built ${{env.MY_FILE}}"

    - uses: actions/upload-artifact@v3 
      with:
        name: ubuntu-16-bin
        path: ${{env.MY_FILE}}

  publish:
    needs: build
    # Only ubuntu can upload via ssh
    runs-on: ubuntu-latest
    
    steps:
    - uses: fabien-ors/files-publish-action@v1
      with:
        host: ${{ secrets.CG_HOST }}
        username: ${{ secrets.CG_USR }}
        password: ${{ secrets.CG_PWD }}
        dest-path: "/var/www/html/wxgl"

